name: build

on:
  workflow_dispatch:
      KERNEL_VER:
        description: 'KERNEL_VER (Specify XANMOD branch to build)'
        required: true
        default: '6.12'

jobs:
  build:
    runs-on: ubuntu-latest
    container: library/archlinux:latest 

    steps:
      - name: Environment Variables
        run: |
          echo 'KERNEL_VER == > ${{ github.event.inputs.KERNEL_VER }}'

      - name: Install packages & setup
        run: |
          pacman -Syu -y
          pacman -S sudo base-devel clang libelf dpkg elfutils git llvm lld bc vim nano cpio -y
          
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Run Build
        run: |
          git clone --depth=1 https://github.com/ghazzor/Xanmod-Kernel-Builder -b main-3 wkdir

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://gitlab.com/xanmod/linux -b ${{ github.event.inputs.KERNEL_VER }} wkdir/kernel/xanmod

      - name: Run Build
        run: |
          cp wkdir/config kernel/xanmod/arch/x86/configs/ng_defconfig
          cd wkdir/kernel/xanmod

          rm -rf vmlinux-gdb.py
          
          ARGS='
          LLVM=1
          LLVM_IAS=1            
          LOCALVERSION=-xanmod-${{ github.event.inputs.KERNEL_VER }}-clang
          '

          make ${ARGS} ng_defconfig
          make ${ARGS} deb-pkg -j$(nproc)
          
          cd ..
          cp xanmod/.config config
          rm -rf xanmod *.gz *.dsc *.buildinfo *.changes

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: Xanmod-${{ github.event.inputs.KERNEL_VER }}
          path: wkdir/kernel/
          compression-level: 9
