name: build

on:
  workflow_dispatch:
    inputs:
      KERNEL_VER:
        description: 'KERNEL_VER (Specify XANMOD branch to build)'
        required: true
        default: '6.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: "🚧 Build Xanmod for omen16"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Environment Variables
        run: |
          echo 'KERNEL_VER == > ${{ github.event.inputs.KERNEL_VER }}'

      - name: Free up Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
                 
      - name: Install packages & setup
        run: |
          sudo apt update
          sudo apt purge firefox -y
          sudo apt upgrade
          
          sudo apt install \
            wget \
            build-essential \
            bison \
            flex \
            pkg-config \
            qtcreator \
            qtbase5-dev \
            qt5-qmake \
            qttools5-dev-tools \
            libssl-dev \
            libncurses-dev \
            git \
            libelf-dev \
            lz4 \
            debhelper \
            dh-virtualenv \
            zstd \
            llvm-19 clang-19 lld-19 \
            elfutils -y

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://gitlab.com/xanmod/linux -b ${{ github.event.inputs.KERNEL_VER }} kernel/xanmod

      - name: Run Build
        run: |
          cp config kernel/xanmod/arch/x86/configs/omen16_defconfig
          cp omen16.config kernel/xanmod/arch/x86/configs/omen16.config
          cp Kconfig.custom kernel/xanmod/
          cp Makefile.custom kernel/xanmod/
          cd kernel/xanmod
          sed -i 's/KBUILD_CFLAGS += -O2/include \$(srctree)\/Makefile.custom/g' Makefile
          echo 'source "Kconfig.custom"' >> Kconfig
          make clean
          rm -rf vmlinux-gdb.py
          export LLVM_SUFFIX=-19
          
          ARGS='
          CC=clang${LLVM_SUFFIX}
          LD=ld.lld${LLVM_SUFFIX}
          LLVM=1
          LLVM_IAS=1
          LLVM_SUFFIX=-19
          '

          make ${ARGS} omen16_defconfig omen16.config
          make ${ARGS} INSTALL_MOD_STRIP=1 dir-pkg -j$(nproc)
          rm -rf tar-install/boot/vmlinux-*
          tar cvf xanmod-${{ github.event.inputs.KERNEL_VER }}-19-omen16.tar ./tar-install/
          xz xanmod-${{ github.event.inputs.KERNEL_VER }}-19-omen16.tar

      - name: Set Release Tag Output
        id: release-tag
        run: echo "NOW=$(date "+%y%m%d%H%M")" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./kernel/xanmod/*tar.xz"
          tag: xanmod-${{ github.event.inputs.KERNEL_VER }}-19-omen16-${{ steps.release-tag.outputs.NOW }}
